title: Rubenelcurioso
baseurl: /
url: 'https://rubenelcurioso.github.io'

markdown: kramdown
theme: null

collections:
  blog:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ''
    values:
      layout: default
